name: simplex_chapter_x
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+17

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  intl: ^0.20.2
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.1.2
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  cached_network_image: ^3.4.1
  pin_code_fields: ^8.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.5
  fluttertoast: ^8.2.12
  web: ^1.1.0
  material_symbols_icons: ^4.2785.1
  firebase_crashlytics: ^4.1.3
  url_launcher: ^6.3.1
  flutter_colorpicker: ^1.1.0
  cloud_functions: ^5.1.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  flutter_app_badge_control: ^0.0.2
  firebase_storage: ^12.3.7
  file_picker: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#104fff"
  adaptive_icon_foreground: "assets/images/android12icon.png"
  image_path: "assets/images/appicon.png"
  min_sdk_android: 19
  web:
    generate: false
    image_path: "assets/images/webimage.png"
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - shorebird.yaml
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
